# Generated by Django 3.2.5 on 2021-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True, help_text='True: Active, False: Inactive')),
            ],
        ),
    ]
