# Generated by Django 3.2.5 on 2021-08-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=400)),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
            ],
        ),
    ]
